#!/usr/bin/env bash
set -e


pip install --no-cache-dir git+https://github.com/AllenNeuralDynamics/aind-dynamic-foraging-basic-analysis@plot_session_in_time_sue


# move VS code data directory into capsule, so it persists
ln -s /root/capsule/code/.vscode/ /.vscode

# install updated version of code-server
VERSION=4.20.1
mkdir /.code-server
cd /.code-server
curl -fL "https://github.com/coder/code-server/releases/download/v$VERSION/code-server-$VERSION-linux-amd64.tar.gz" \
  | tar -xvz
ln -s /.code-server/code-server-$VERSION-linux-amd64/bin/code-server  /usr/bin/code-server
cd -