#!/usr/bin/env bash
set -e


pip install --no-deps --no-cache-dir git+https://github.com/AllenNeuralDynamics/aind-dynamic-foraging-basic-analysis@b3e2e4f29f062764f9a40bfdc630dd0b6f039989

# clone external analysis repo used via source-path imports
EXTERNAL_ROOT="src/external"
BEH_EPHYS_REPO_DIR="$EXTERNAL_ROOT/aind-beh-ephys-analysis"
BEH_EPHYS_REPO_URL="https://github.com/AllenNeuralDynamics/aind-beh-ephys-analysis.git"
BEH_EPHYS_COMMIT="c1af968002a4e7d85a35fdc455ab849617f57874"

mkdir -p "$EXTERNAL_ROOT"

if [ ! -d "$BEH_EPHYS_REPO_DIR/.git" ]; then
  # shallow clone for speed
  git clone --depth 1 "$BEH_EPHYS_REPO_URL" "$BEH_EPHYS_REPO_DIR"
  git -C "$BEH_EPHYS_REPO_DIR" fetch --depth 1 origin "$BEH_EPHYS_COMMIT"
else
  git -C "$BEH_EPHYS_REPO_DIR" fetch origin "$BEH_EPHYS_COMMIT"
fi

# checkout the exact commit (detached HEAD)
git -C "$BEH_EPHYS_REPO_DIR" checkout "$BEH_EPHYS_COMMIT"


# move VS code data directory into capsule, so it persists
ln -s /root/capsule/code/.vscode/ /.vscode

# install updated version of code-server
VERSION=4.20.1
mkdir /.code-server
cd /.code-server
curl -fL "https://github.com/coder/code-server/releases/download/v$VERSION/code-server-$VERSION-linux-amd64.tar.gz" \
  | tar -xvz
ln -s /.code-server/code-server-$VERSION-linux-amd64/bin/code-server  /usr/bin/code-server
cd -